export interface DilemmaRecord {
  id: string;
  dilemma: string;    // 困境名称
  option: string;     // 选项名称
  result: string;     // 结果
  map: string;        // 出现的地图
  evaluation: string; // 评价
}

export const DILEMMA_DATA: DilemmaRecord[] = [
  { id: "1", dilemma: "聪慧的头颅", option: "专心执行任务", result: "探险行动时长：-4天, 经验奖励+10%", map: "白骨带", evaluation: "正面" },
  { id: "2", dilemma: "直升机失窃案", option: "随便修修", result: "直升机受损", map: "白骨带", evaluation: "负面" },
  { id: "3", dilemma: "直升机失窃案", option: "修理直升机(机械学)", result: "未知", map: "白骨带", evaluation: "中性" },
  { id: "4", dilemma: "直升机失窃案", option: "找回零件", result: "【伤病】碎脸", map: "白骨带", evaluation: "伤病" },
  { id: "5", dilemma: "热梦", option: "让TA走吧", result: "【伤病】冻脚", map: "已知宇宙, 白骨带", evaluation: "伤病" },
  { id: "6", dilemma: "热梦", option: "捆起来装好(荒野求生)", result: "经验奖励+10%", map: "已知宇宙, 白骨带", evaluation: "正面" },
  { id: "7", dilemma: "热梦", option: "抓住TA", result: "士气低落", map: "已知宇宙, 白骨带", evaluation: "负面" },
  { id: "8", dilemma: "大雪封路", option: "爬过冰墙", result: "【伤病】冻脚", map: "白骨带", evaluation: "伤病" },
  { id: "9", dilemma: "大雪封路", option: "铲开冰墙", result: "经验奖励+10%", map: "白骨带", evaluation: "正面" },
  { id: "10", dilemma: "大雪封路", option: "滑滑梯(调查勘探)", result: "探险行动时长：-4天, 士气高涨", map: "白骨带", evaluation: "正面" },
  { id: "11", dilemma: "探险困境", option: "快跑", result: "【伤病】痛痛腿", map: "白骨带", evaluation: "伤病" },
  { id: "12", dilemma: "探险困境", option: "搭建避难所", result: "士气高涨", map: "白骨带", evaluation: "正面" },
  { id: "13", dilemma: "探险困境", option: "随心飞", result: "失踪", map: "白骨带", evaluation: "失踪" },
  { id: "14", dilemma: "夺命风滚草", option: "准备迎战", result: "失踪", map: "白骨带", evaluation: "失踪" },
  { id: "15", dilemma: "夺命风滚草", option: "静观其变", result: "经验奖励+5%", map: "白骨带", evaluation: "正面" },
  { id: "16", dilemma: "夺命风滚草", option: "热烈欢迎", result: "【伤病】碎脸", map: "白骨带", evaluation: "伤病" },
  { id: "17", dilemma: "压力蛇大", option: "一点小雨", result: "【伤病】蛇咬, 士气低落", map: "白骨带", evaluation: "伤病,负面" },
  { id: "18", dilemma: "压力蛇大", option: "蛇?有毒?快跑!", result: "展示品品质-1", map: "白骨带", evaluation: "负面" },
  { id: "19", dilemma: "压力蛇大", option: "几条蛇而已", result: "特质：与蛇共舞", map: "白骨带", evaluation: "正面" },
  { id: "20", dilemma: "地洞惊魂", option: "让TA自己爬出来", result: "【伤病】痛痛腿", map: "白骨带", evaluation: "伤病" },
  { id: "21", dilemma: "地洞惊魂", option: "爬去帮忙", result: "【伤病】痛痛腿", map: "白骨带", evaluation: "伤病" },
  { id: "22", dilemma: "地洞惊魂", option: "紧急救援(荒野求生)", result: "经验奖励+5%", map: "白骨带", evaluation: "正面" },
  { id: "23", dilemma: "该换袜子了", option: "送去新袜子", result: "士气高涨, 金钱-700", map: "白骨带", evaluation: "中性" },
  { id: "24", dilemma: "该换袜子了", option: "再忍一忍", result: "士气低落", map: "白骨带", evaluation: "负面" },
  { id: "25", dilemma: "该换袜子了", option: "特质袜子(荒野求生)", result: "士气高涨", map: "白骨带", evaluation: "正面" },
  { id: "26", dilemma: "泡泡危机", option: "造桥而过", result: "探险行动时长：+7天, 经验奖励+10%", map: "白骨带", evaluation: "负面,正面" },
  { id: "27", dilemma: "泡泡危机", option: "涉水而过", result: "士气高涨", map: "白骨带", evaluation: "正面" },
  { id: "28", dilemma: "阳光直射", option: "高强度日光浴", result: "展示品品质-1", map: "白骨带", evaluation: "负面" },
  { id: "29", dilemma: "阳光直射", option: "做好遮阳，继续上路", result: "经验奖励+5%", map: "白骨带", evaluation: "正面" },
  { id: "30", dilemma: "阳光直射", option: "寻找阴凉处(调查勘探)", result: "士气高涨", map: "白骨带", evaluation: "正面" },
  { id: "31", dilemma: "荒野求蛇", option: "喂他", result: "【伤病】蛇咬", map: "白骨带", evaluation: "伤病" },
  { id: "32", dilemma: "荒野求蛇", option: "吃它", result: "士气高涨", map: "白骨带", evaluation: "正面" },
  { id: "33", dilemma: "无聊游戏", option: "返回基地", result: "士气高涨, 金钱-1500, 探险行动时长+7天", map: "双点海, 白骨带", evaluation: "中性" },
  { id: "34", dilemma: "无聊游戏", option: "别想游戏了", result: "士气低落", map: "双点海, 白骨带", evaluation: "负面" },
  { id: "35", dilemma: "无聊游戏", option: "找点其他东西玩(分析)", result: "士气高涨", map: "双点海, 白骨带", evaluation: "正面" },
  { id: "36", dilemma: "荒凉小镇", option: "过去打个招呼", result: "士气高涨", map: "白骨带", evaluation: "正面" },
  { id: "37", dilemma: "荒凉小镇", option: "绕开", result: "无事发生", map: "白骨带", evaluation: "中性" },
  { id: "38", dilemma: "急火攻心", option: "助其清醒", result: "探险行动时长：+5天", map: "白骨带", evaluation: "负面" },
  { id: "39", dilemma: "急火攻心", option: "静观其变", result: "士气高涨, 探险行动时长：+5天", map: "白骨带", evaluation: "中性" },
  { id: "40", dilemma: "无食生非", option: "来点干酪片!", result: "士气高涨, 展示品品质-1", map: "白骨带", evaluation: "中性" },
  { id: "41", dilemma: "无食生非", option: "克服饥饿", result: "展示品特质：快速损坏", map: "白骨带", evaluation: "负面" },
  { id: "42", dilemma: "金光闪闪", option: "没有时间", result: "士气低落", map: "双点海", evaluation: "负面" },
  { id: "43", dilemma: "金光闪闪", option: "过去看看", result: "金钱+10000, 探险行动时长：+1天, 探险行动时长：+3天", map: "双点海", evaluation: "中性" },
  { id: "44", dilemma: "鲨鱼开饭", option: "用海藻包扎伤口(荒野求生)", result: "士气高涨, 经验奖励+15%", map: "双点海", evaluation: "正面" },
  { id: "45", dilemma: "鲨鱼开饭", option: "别放在心上", result: "【伤病】痛痛腿", map: "双点海", evaluation: "伤病" },
  { id: "46", dilemma: "鲨鱼开饭", option: "送TA回去", result: "探险行动时长：+4天, 探险行动时长：+2天", map: "双点海", evaluation: "负面" },
  { id: "47", dilemma: "巨齿危机", option: "全速前进", result: "探险行动时长：-7天", map: "双点海", evaluation: "正面" },
  { id: "48", dilemma: "巨齿危机", option: "灵活闪避", result: "展示品品质-1, 获得特质", map: "双点海", evaluation: "负面,中性" },
  { id: "49", dilemma: "巨齿危机", option: "藏起来(荒野求生)", result: "特质：拥抱大海(避免晕船)", map: "双点海", evaluation: "正面" },
  { id: "50", dilemma: "印了个钱", option: "开个价吧", result: "金钱-2000, 展示品：印钱机", map: "双点海", evaluation: "负面,正面" },
  { id: "51", dilemma: "印了个钱", option: "没兴趣", result: "无事发生", map: "双点海", evaluation: "中性" },
  { id: "52", dilemma: "海藻之缚", option: "救回展示品", result: "展示品品质+1, 士气低落", map: "双点海", evaluation: "中性" },
  { id: "53", dilemma: "海藻之缚", option: "解救队友", result: "士气高涨, 探险行动时长：-4天", map: "双点海", evaluation: "正面" },
  { id: "54", dilemma: "来一圈", option: "爬进去调查", result: "【伤病】碎脸", map: "低端科技地穴", evaluation: "伤病" },
  { id: "55", dilemma: "来一圈", option: "查看显示屏", result: "金钱+5000, 经验奖励+5%", map: "低端科技地穴", evaluation: "正面" },
  { id: "56", dilemma: "来点水果", option: "味道不错", result: "【伤病】拘泥症", map: "低端科技地穴", evaluation: "伤病" },
  { id: "57", dilemma: "来点水果", option: "喂给老鼠吃", result: "【伤病】碎脸", map: "低端科技地穴", evaluation: "伤病" },
  { id: "58", dilemma: "来点水果", option: "分析水果(分析)", result: "经验奖励+10%", map: "低端科技地穴", evaluation: "正面" },
  { id: "59", dilemma: "天气相随", option: "“下雨”按钮", result: "金钱+5000, 士气高涨", map: "低端科技地穴", evaluation: "正面" },
  { id: "60", dilemma: "天气相随", option: "“打雷”按钮", result: "【伤病】碎脸", map: "低端科技地穴", evaluation: "伤病" },
  { id: "61", dilemma: "天气相随", option: "“乌云”按钮", result: "【疾病】蓝色忧郁", map: "低端科技地穴", evaluation: "疾病" },
  { id: "62", dilemma: "恐惧之勺", option: "质问勺子!", result: "【诅咒】欢迎鬼临", map: "冥界", evaluation: "诅咒" },
  { id: "63", dilemma: "恐惧之勺", option: "谁要这鬼餐具!", result: "士气低落", map: "冥界", evaluation: "负面" },
  { id: "64", dilemma: "恐惧之勺", option: "和勺子讲道理", result: "士气高涨", map: "冥界", evaluation: "正面" },
  { id: "65", dilemma: "偶遇侍从", option: "共舞一曲", result: "冥界祝福", map: "冥界", evaluation: "正面" },
  { id: "66", dilemma: "偶遇侍从", option: "嘲笑他", result: "【诅咒】创伤性XP综合症", map: "冥界", evaluation: "诅咒" },
  { id: "67", dilemma: "偶遇侍从", option: "和他一起笑", result: "经验奖励+10%", map: "冥界", evaluation: "正面" },
  { id: "68", dilemma: "因祸得福", option: "寻求人生建议", result: "冥界祝福, 金钱-500", map: "冥界", evaluation: "中性" },
  { id: "69", dilemma: "因祸得福", option: "问路", result: "探险行动时长：-7天", map: "冥界", evaluation: "正面" },
  { id: "70", dilemma: "因祸得福", option: "无视", result: "无事发生", map: "冥界", evaluation: "中性" },
  { id: "71", dilemma: "这手不错", option: "跑啊啊啊!", result: "展示品品质-1", map: "冥界", evaluation: "负面" },
  { id: "72", dilemma: "这手不错", option: "握手", result: "探险行动时长：-3天", map: "冥界", evaluation: "正面" },
  { id: "73", dilemma: "要钱还是要命", option: "选择钱袋", result: "金钱-5000", map: "冥界", evaluation: "负面" },
  { id: "74", dilemma: "要钱还是要命", option: "选择复活卷轴", result: "生存卷轴（免除失踪）", map: "冥界", evaluation: "正面" },
  { id: "75", dilemma: "应该没看到我们吧", option: "引开它", result: "探险行动时长：-7天, 探险行动时长：+7天", map: "已知宇宙", evaluation: "中性" },
  { id: "76", dilemma: "应该没看到我们吧", option: "吓跑它", result: "【伤病】满脚奶酪", map: "已知宇宙", evaluation: "伤病" },
  { id: "77", dilemma: "走进未知", option: "无视太空舱", result: "探险行动时长：+6天", map: "已知宇宙", evaluation: "负面" },
  { id: "78", dilemma: "走进未知", option: "出手相助（二随一）", result: "士气高涨, 金钱+5000", map: "已知宇宙", evaluation: "正面" },
  { id: "79", dilemma: "走进未知", option: "回收太空舱（概率出疾病）", result: "探险行动时长：+2天, 经验奖励+5%, 【疾病】蓝色忧郁", map: "已知宇宙", evaluation: "负面,正面,疾病" },
  { id: "80", dilemma: "双输局面", option: "稳扎稳打", result: "展示品品质-1", map: "已知宇宙", evaluation: "负面" },
  { id: "81", dilemma: "双输局面", option: "把队员装在展示品上", result: "士气低落", map: "已知宇宙", evaluation: "负面" },
  { id: "82", dilemma: "双输局面", option: "派人去和火焰谈判", result: "失踪", map: "已知宇宙", evaluation: "失踪" },
  { id: "83", dilemma: "左嗡右摇", option: "草丛", result: "【伤病】痛痛腿", map: "已知宇宙", evaluation: "伤病" },
  { id: "84", dilemma: "左嗡右摇", option: "洞穴", result: "【诅咒】歃血为呱", map: "已知宇宙", evaluation: "诅咒" },
  { id: "85", dilemma: "“重”任在肩", option: "一群懒鬼", result: "【疾病】陨石螨虫", map: "已知宇宙", evaluation: "疾病" },
  { id: "86", dilemma: "“重”任在肩", option: "休息", result: "展示品品质-2", map: "已知宇宙", evaluation: "负面" },
  { id: "87", dilemma: "“重”任在肩", option: "派遣紧急撤离组(飞行员之翼）", result: "士气高涨, 探险行动时长：-7天", map: "已知宇宙", evaluation: "正面" },
  { id: "88", dilemma: "奶酪，我来了", option: "吃掉这些奶酪", result: "【伤病】满脚奶酪", map: "已知宇宙", evaluation: "伤病" },
  { id: "89", dilemma: "奶酪，我来了", option: "伸出援手", result: "士气高涨, 【伤病】满脚奶酪", map: "已知宇宙", evaluation: "正面,伤病" },
  { id: "90", dilemma: "奶酪，我来了", option: "自求多福吧", result: "士气低落, 【伤病】满脚奶酪", map: "已知宇宙", evaluation: "负面,伤病" },
  { id: "91", dilemma: "触手突袭", option: "加速逃脱", result: "无事发生", map: "双点海", evaluation: "中性" },
  { id: "92", dilemma: "触手突袭", option: "击退乌贼（随机）", result: "无事发生, 探险行动时长：+2天", map: "双点海", evaluation: "中性,负面" },
  { id: "93", dilemma: "触手突袭", option: "唱船歌（概率无事发生）", result: "士气高涨", map: "双点海", evaluation: "正面" },
  { id: "94", dilemma: "光芒闪动", option: "跟着光走", result: "性能模块（强力固定）, 金钱-500", map: "已知宇宙", evaluation: "中性" },
  { id: "95", dilemma: "光芒闪动", option: "远离光芒", result: "展示品品质-1", map: "已知宇宙", evaluation: "负面" },
  { id: "96", dilemma: "升级套餐", option: "听起来不错", result: "探险行动时长：+1天, 金钱-500, 展示品品质+1", map: "双点海", evaluation: "负面,正面" },
  { id: "97", dilemma: "升级套餐", option: "狠狠嘲笑", result: "展示品的品质-1", map: "双点海", evaluation: "负面" },
  { id: "98", dilemma: "升级套餐", option: "讨价还价", result: "探险行动时长：+12天, 展示品品质+1", map: "双点海", evaluation: "负面,正面" },
  { id: "99", dilemma: "扬眉吐气", option: "无视", result: "经验奖励+5%", map: "低端科技地穴", evaluation: "正面" },
  { id: "100", dilemma: "扬眉吐气", option: "放它出来", result: "【疾病】连眉", map: "低端科技地穴", evaluation: "疾病" },
  { id: "101", dilemma: "扬眉吐气", option: "麻醉后进行评估（分析）", result: "【疾病】连眉", map: "低端科技地穴", evaluation: "疾病" },
  { id: "102", dilemma: "奶酪小行星", option: "炸出一条路", result: "随行物品（5x职等奶酪）", map: "已知宇宙", evaluation: "正面" },
  { id: "103", dilemma: "奶酪小行星", option: "穿过小行星群", result: "特质：知名奶酪", map: "已知宇宙", evaluation: "正面" },
  { id: "104", dilemma: "奶酪小行星", option: "派遣勤杂工去奶酪主舰求援（概率金钱）", result: "失踪, 金钱+10000", map: "已知宇宙", evaluation: "失踪,正面" },
  { id: "105", dilemma: "烦人鬼", option: "吓跑它", result: "无事发生", map: "冥界", evaluation: "中性" },
  { id: "106", dilemma: "烦人鬼", option: "向鬼魂求助", result: "展示品品质+1, 探险行动时长：-1天", map: "冥界", evaluation: "正面" },
  { id: "107", dilemma: "烦人鬼", option: "跟它讲道理", result: "经验奖励+15%", map: "冥界", evaluation: "正面" },
  { id: "108", dilemma: "凡事讲概率", option: "冒险穿越（随机一项）", result: "士气低落, 无事发生", map: "已知宇宙", evaluation: "负面,中性" },
  { id: "109", dilemma: "凡事讲概率", option: "采取回避行动（随机一项）", result: "直升机受损, 【伤病】碎脸", map: "已知宇宙", evaluation: "负面,伤病" },
  { id: "110", dilemma: "凡事讲概率", option: "二次确认（飞行员之翼）（失踪或其他2项）", result: "失踪, 经验奖励+1%, 探险行动时长：+5天, 探险行动时长：+2天", map: "已知宇宙", evaluation: "失踪,中性" },
  { id: "111", dilemma: "蛇宝宝", option: "收养它", result: "金钱-1000, 探险行动时长：+5天", map: "白骨带", evaluation: "负面" },
  { id: "112", dilemma: "蛇宝宝", option: "这是陷阱！", result: "士气高涨", map: "白骨带", evaluation: "正面" },
  { id: "113", dilemma: "犯法公民", option: "帮助女人", result: "探险行动时长：+2天, 金钱-500", map: "冥界", evaluation: "负面" },
  { id: "114", dilemma: "犯法公民", option: "帮助守卫", result: "金钱+1000, 经验奖励+5%", map: "冥界", evaluation: "负面,正面" },
  { id: "115", dilemma: "犯法公民", option: "对她做鬼脸", result: "【诅咒】歃血为呱", map: "冥界", evaluation: "诅咒" },
  { id: "116", dilemma: "失算的巫师", option: "救下菠萝", result: "【诅咒】歃血为呱", map: "冥界", evaluation: "诅咒" },
  { id: "117", dilemma: "失算的巫师", option: "冲向巫师", result: "失踪", map: "冥界", evaluation: "失踪" },
  { id: "118", dilemma: "失算的巫师", option: "询问缘由", result: "金钱+5000, 经验奖励+5%", map: "冥界", evaluation: "正面" },
  { id: "119", dilemma: "炽热陨星", option: "硬碰硬", result: "直升机受损, 【伤病】碎脸", map: "已知宇宙", evaluation: "负面,伤病" },
  { id: "120", dilemma: "炽热陨星", option: "发射激光", result: "直升机受损, 士气低落", map: "已知宇宙", evaluation: "负面" },
  { id: "121", dilemma: "炽热陨星", option: "横穿彗星（飞行员之翼）", result: "经验奖励+10%", map: "已知宇宙", evaluation: "正面" },
  { id: "122", dilemma: "五星级酒店", option: "我们得救了", result: "士气高涨", map: "白骨带", evaluation: "正面" },
  { id: "123", dilemma: "五星级酒店", option: "这是海市蜃楼", result: "士气低落, 经验奖励+5%", map: "白骨带", evaluation: "负面,正面" },
  { id: "124", dilemma: "蔚蓝光辉", option: "保持原计划！", result: "经验奖励+5% ", map: "冥界", evaluation: "正面" },
  { id: "125", dilemma: "蔚蓝光辉", option: "穿过传送门！", result: "士气高涨, 探险行动时长：-3天, 展示品品质+1", map: "冥界", evaluation: "正面" },
  { id: "126", dilemma: "金矿", option: "把手按在传感器上", result: "【疾病】点金术", map: "冥界", evaluation: "疾病" },
  { id: "127", dilemma: "金矿", option: "带走一尊雕像", result: "金钱+7500", map: "冥界", evaluation: "正面" },
  { id: "128", dilemma: "邪恶装置", option: "使用装置", result: "探险行动时长：+7天", map: "已知宇宙", evaluation: "负面" },
  { id: "129", dilemma: "邪恶装置", option: "保持距离", result: "经验奖励+5%, 直升机受损", map: "已知宇宙", evaluation: "中性" },
  { id: "130", dilemma: "邪恶装置", option: "调查太空舱（分析）", result: "探险行动时长：-5天, 士气高涨", map: "已知宇宙", evaluation: "正面" },
  { id: "131", dilemma: "战还是逃", option: "先下手为强", result: "直升机受损, 展示品品质-1", map: "已知宇宙", evaluation: "负面" },
  { id: "132", dilemma: "战还是逃", option: "带我们去见你们的首领", result: "探险行动时长：-7天", map: "已知宇宙", evaluation: "正面" },
  { id: "133", dilemma: "战还是逃", option: "更改路线", result: "探险行动时长：+7天", map: "已知宇宙", evaluation: "负面" },
  { id: "134", dilemma: "寻宝之旅", option: "进入裂隙寻找宝藏", result: "探险行动时长：+3天, 金钱+5000 或 探险行动时长：+3天, 士气低落", map: "白骨带", evaluation: "负面,正面" },
  { id: "135", dilemma: "寻宝之旅", option: "跳过裂隙", result: "【伤病】痛痛腿", map: "白骨带", evaluation: "伤病" },
  { id: "136", dilemma: "寻宝之旅", option: "返回直升机！", result: "无事发生", map: "白骨带", evaluation: "中性" },
  { id: "137", dilemma: "巫术时刻", option: "当然可以，难道他还会吃人？", result: "失踪, 随行物品（疾病万能药）", map: "冥界", evaluation: "失踪,正面" },
  { id: "138", dilemma: "巫术时刻", option: "都这么晚了啊？", result: "经验奖励+5%", map: "冥界", evaluation: "正面" },
  { id: "139", dilemma: "怪异青蛙", option: "引开注意", result: "失踪", map: "已知宇宙", evaluation: "失踪" },
  { id: "140", dilemma: "怪异青蛙", option: "近距离观察", result: "未知", map: "已知宇宙", evaluation: "中性" },
  { id: "141", dilemma: "怪异青蛙", option: "送展示品给呱星人", result: "展示品品质+1", map: "已知宇宙", evaluation: "正面" },
  { id: "142", dilemma: "啊！龙卷风！", option: "快跑", result: "探索行动时长：-6天, 【伤病】痛痛腿", map: "白骨带", evaluation: "正面,伤病" },
  { id: "143", dilemma: "啊！龙卷风！", option: "搭建避难所（概率品质-1）", result: "探索行动时长：-6天, 经验奖励+5%, 展示品品质-1", map: "白骨带", evaluation: "中性" },
  { id: "144", dilemma: "啊！龙卷风！", option: "随心飞", result: "失踪", map: "白骨带", evaluation: "失踪" },
  { id: "145", dilemma: "这根藤不好惹", option: "大战杂草", result: "失踪", map: "白骨带", evaluation: "失踪" },
  { id: "146", dilemma: "这根藤不好惹", option: "撤退！", result: "经验奖励+10%", map: "白骨带", evaluation: "正面" },
  { id: "147", dilemma: "诡异灵体", option: "恐惧只存在于心中", result: "经验奖励+5%, 【诅咒】欢迎鬼临", map: "冥界", evaluation: "正面,诅咒" },
  { id: "148", dilemma: "诡异灵体", option: "安抚灵体（荒野求生）", result: "冥界祝福, 士气高涨", map: "冥界", evaluation: "正面" },
  { id: "149", dilemma: "诡异灵体", option: "还是撤吧", result: "经验奖励+5%", map: "冥界", evaluation: "正面" },
  { id: "150", dilemma: "长枪林立", option: "攻击他的左侧", result: "士气低落, 【伤病】碎脸", map: "冥界", evaluation: "负面,伤病" },
  { id: "151", dilemma: "长枪林立", option: "攻击他的右侧（巡逻监管）", result: "冥界祝福", map: "冥界", evaluation: "正面" },
  { id: "152", dilemma: "长枪林立", option: "逃跑！", result: "【诅咒】创伤性XP综合症", map: "冥界", evaluation: "诅咒" },
  { id: "153", dilemma: "押韵还是押命", option: "听起来不错", result: "探险行动时长：-7天, 【诅咒】歃血为呱", map: "冥界", evaluation: "正面,诅咒" },
  { id: "154", dilemma: "押韵还是押命", option: "表示感激", result: "探险行动时长：-7天, 冥界祝福", map: "冥界", evaluation: "正面" },
  { id: "155", dilemma: "押韵还是押命", option: "完全无视！", result: "无事发生", map: "冥界", evaluation: "中性" },
  { id: "156", dilemma: "聪慧的头颅", option: "取回药瓶", result: "特质：身强力壮, 特质：厕所狂徒", map: "白骨带", evaluation: "中性" },
  { id: "157", dilemma: "刺头危机", option: "派出科学专家", result: "失踪", map: "低端科技地穴", evaluation: "失踪" },
  { id: "158", dilemma: "刺头危机", option: "派出勤杂工", result: "失踪", map: "低端科技地穴", evaluation: "失踪" },
  { id: "159", dilemma: "黑旗", option: "扔点东西下去", result: "金钱-5000", map: "双点海", evaluation: "负面" },
  { id: "160", dilemma: "黑旗", option: "走开（巡逻监管）", result: "经验奖励+10%", map: "双点海", evaluation: "正面" },
  { id: "161", dilemma: "黑旗", option: "逃跑", result: "展示品品质-1", map: "双点海", evaluation: "负面" },
  { id: "162", dilemma: "修复还是重锤", option: "温柔修复", result: "探险行动时长：+3天, 展示品品质+1", map: "冥界, 双点海", evaluation: "负面,正面" },
  { id: "163", dilemma: "修复还是重锤", option: "重锤去除", result: "未知", map: "冥界, 双点海", evaluation: "中性" },
  { id: "164", dilemma: "修复还是重锤", option: "光速修复（机械学）", result: "展示品品质+1", map: "冥界, 双点海", evaluation: "正面" },
  { id: "165", dilemma: "闻声辩路", option: "别去听", result: "展示品品质-1", map: "已知宇宙", evaluation: "负面" },
  { id: "166", dilemma: "闻声辩路", option: "美妙的歌声！", result: "探险行动时长：+1天, 士气高涨, 【疾病】陨石螨虫", map: "已知宇宙", evaluation: "负面,正面,疾病" },
  { id: "167", dilemma: "闻声辩路", option: "远处倾听（调查勘探）", result: "探险行动时长：+2天, 士气高涨", map: "已知宇宙", evaluation: "负面,正面" },
  { id: "168", dilemma: "加冰", option: "等待救援", result: "展示品品质-1", map: "低端科技地穴", evaluation: "负面" },
  { id: "169", dilemma: "加冰", option: "取暖（荒野求生）", result: "经验奖励+5%", map: "低端科技地穴", evaluation: "正面" },
  { id: "170", dilemma: "加冰", option: "踹门", result: "经验奖励+5%或【伤病】痛痛腿", map: "低端科技地穴", evaluation: "中性" },
  { id: "171", dilemma: "巨喵来袭", option: "快逃", result: "未知", map: "双点海", evaluation: "中性" },
  { id: "172", dilemma: "巨喵来袭", option: "嘘……别出声", result: "经验奖励+5%", map: "双点海", evaluation: "正面" },
  { id: "173", dilemma: "巨喵来袭", option: "慧眼如炬（巡逻监管）", result: "未知", map: "双点海", evaluation: "中性" },
  { id: "174", dilemma: "地心之城", option: "偷偷溜走", result: "未知", map: "白骨带", evaluation: "中性" },
  { id: "175", dilemma: "地心之城", option: "送点零食", result: "未知", map: "白骨带", evaluation: "中性" },
  { id: "176", dilemma: "地心之城", option: "问路", result: "士气高涨, 探险行动时长：-7天", map: "白骨带", evaluation: "正面" },
  { id: "177", dilemma: "玩水", option: "来点大水花", result: "经验奖励+50%, 【疾病】泥铲炎", map: "白骨带", evaluation: "正面,疾病" },
  { id: "178", dilemma: "玩水", option: "有风险继续前进", result: "士气低落", map: "白骨带", evaluation: "负面" },
  { id: "179", dilemma: "玩水", option: "研究水样", result: "未知", map: "白骨带", evaluation: "中性" },
  { id: "180", dilemma: "声东击西", option: "给她指路", result: "金钱-500, 直升机受损", map: "冥界", evaluation: "负面" },
  { id: "181", dilemma: "声东击西", option: "无视老奶奶", result: "士气低落。", map: "冥界", evaluation: "负面" },
  { id: "182", dilemma: "声东击西", option: "让孩子们来帮助老妇人", result: "经验奖励+5%, 金钱-50, 探险行动时长：+1天", map: "冥界", evaluation: "中性" },
  { id: "183", dilemma: "走到哪塌到哪", option: "塌方了！快跑！", result: "士气高涨", map: "白骨带", evaluation: "正面" },
  { id: "184", dilemma: "走到哪塌到哪", option: "应该是错觉吧", result: "探险行动时长：+3天,展品特质：快速损坏", map: "白骨带", evaluation: "负面" },
  { id: "185", dilemma: "走到哪塌到哪", option: "保护展示品", result: "【伤病】痛痛腿, 探险行动时长：+2天", map: "白骨带", evaluation: "伤病,负面" },
  { id: "186", dilemma: "水，给我水……", option: "浅尝一小口海水", result: "【疾病】泥铲炎", map: "双点海", evaluation: "疾病" },
  { id: "187", dilemma: "水，给我水……", option: "空投", result: "士气高涨, 金钱-1250", map: "双点海", evaluation: "正面" },
  { id: "188", dilemma: "白日热梦", option: "救下探险队员", result: "展示品品质-1", map: "已知宇宙", evaluation: "负面" },
  { id: "189", dilemma: "白日热梦", option: "救下展示品", result: "失踪", map: "已知宇宙", evaluation: "失踪" },
  { id: "190", dilemma: "生人勿入，生鬼也不行", option: "忍一时", result: "经验奖励+5%", map: "冥界", evaluation: "正面" },
  { id: "191", dilemma: "生人勿入，生鬼也不行", option: "正面回应", result: "失踪,士气低落", map: "冥界", evaluation: "负面,失踪" },
  { id: "192", dilemma: "生人勿入，生鬼也不行", option: "堵住耳朵（荒野求生）", result: "金钱-150, 探险行动时长：+1天, 经验奖励+5%", map: "冥界", evaluation: "负面,正面" },
  { id: "193", dilemma: "豪饮", option: "在臭水坑里装满水壶", result: "【疾病】拘泥症", map: "白骨带", evaluation: "负面" },
  { id: "194", dilemma: "豪饮", option: "空投", result: "金钱-1000", map: "白骨带", evaluation: "负面" },
  { id: "195", dilemma: "壮观的沉船", option: "不管他", result: "无事发生", map: "双点海", evaluation: "负面" },
  { id: "196", dilemma: "壮观的沉船", option: "寻宝", result: "探险行动时长：+7天, 金钱+15000", map: "双点海", evaluation: "负面,正面" },
  { id: "197", dilemma: "幻象重重", option: "想游就游吧", result: "【伤病】痛痛腿", map: "白骨带", evaluation: "负面" },
  { id: "198", dilemma: "幻象重重", option: "拦住他", result: "【伤病】痛痛腿", map: "白骨带", evaluation: "负面" },
  { id: "199", dilemma: "宝藏时刻", option: "打开宝箱", result: "【伤病】碎脸", map: "焦土世界", evaluation: "负面" },
  { id: "200", dilemma: "宝藏时刻", option: "当做没看到", result: "经验奖励+100%", map: "焦土世界", evaluation: "正面" },
  { id: "201", dilemma: "宝藏时刻", option: "探测（龙之智慧）", result: "未知", map: "焦土世界", evaluation: "中性" },
  { id: "202", dilemma: "黑洞惊魂", option: "反向推进", result: "展示品品质-1", map: "已知宇宙", evaluation: "负面" },
  { id: "203", dilemma: "黑洞惊魂", option: "徒劳的抵抗", result: "士气高涨, 直升机受损, 士气低落, 探险行动时长：+7天", map: "已知宇宙", evaluation: "中性" },
  { id: "204", dilemma: "脚部宕机", option: "再撑一下", result: "士气高涨, 【伤病】冻脚, 经验奖励+10%", map: "已知宇宙", evaluation: "正面,伤病" },
  { id: "205", dilemma: "脚部宕机", option: "修补靴子", result: "直升机受损, 探险行动时长：+7天, 经验奖励+5%", map: "已知宇宙", evaluation: "负面,正面" },
  { id: "206", dilemma: "脚部宕机", option: "快速修复（机械学）", result: "士气高涨", map: "已知宇宙", evaluation: "正面" },
  { id: "207", dilemma: "王国收入", option: "交税", result: "金钱-5000, 随行物品（力量魔药）", map: "焦土世界", evaluation: "负面,正面" },
  { id: "208", dilemma: "王国收入", option: "逃税", result: "耻辱囚枷", map: "焦土世界", evaluation: "中性" },
  { id: "209", dilemma: "王国收入", option: "可我就是国王啊？（王国之冠）", result: "未知", map: "焦土世界", evaluation: "中性" },
  { id: "210", dilemma: "巨魔为谁收债", option: "抢钱", result: "未知", map: "焦土世界", evaluation: "中性" },
  { id: "211", dilemma: "巨魔为谁收债", option: "失物我来领", result: "随行物品（敏捷魔药）", map: "焦土世界", evaluation: "正面" },
  { id: "212", dilemma: "女巫之夜", option: "不了，谢谢", result: "经验奖励+25% ", map: "焦土世界", evaluation: "正面" },
  { id: "213", dilemma: "女巫之夜", option: "喝几杯再走", result: "特质：聪慧", map: "焦土世界", evaluation: "正面" },
  { id: "214", dilemma: "女巫之夜", option: "有人喜欢听鲁特宝琴吗？（鲁特宝琴）", result: "未知", map: "焦土世界", evaluation: "中性" },
  { id: "215", dilemma: "美中不足", option: "美中不足", result: "未知", map: "焦土世界", evaluation: "中性" },
  { id: "216", dilemma: "美中不足", option: "把石头圈补好", result: "特质：矮人庇佑", map: "焦土世界", evaluation: "正面" },
  { id: "217", dilemma: "美中不足", option: "跳支小舞（矮人庇佑）", result: "未知", map: "焦土世界", evaluation: "中性" },
  { id: "218", dilemma: "切断，突围", option: "带走龙爪碎片", result: "未知", map: "焦土世界", evaluation: "中性" },
  { id: "219", dilemma: "切断，突围", option: "带走烧焦的龙鳞", result: "特质：火焰护盾, 特质：破军杀龙", map: "焦土世界", evaluation: "正面" },
  { id: "220", dilemma: "无火不起烟", option: "走近路", result: "探险行动时长:-6天,生物多样性等级降低", map: "焦土世界", evaluation: "中性" },
  { id: "221", dilemma: "无火不起烟", option: "绕远路", result: "未知", map: "焦土世界", evaluation: "中性" },
  { id: "222", dilemma: "无火不起烟", option: "安全路线（荒野求生）", result: "经验奖励+5%", map: "焦土世界", evaluation: "正面" },
  { id: "223", dilemma: "烈焰突袭", option: "真的是恶龙吗？", result: "经验奖励+150%", map: "焦土世界", evaluation: "正面" },
  { id: "224", dilemma: "烈焰突袭", option: "是一条恶龙！", result: "未知", map: "焦土世界", evaluation: "中性" },
  { id: "225", dilemma: "烈焰突袭", option: "看我！（火焰护盾）", result: "士气高涨, 经验奖励+350%", map: "焦土世界", evaluation: "正面" },
  { id: "226", dilemma: "情况危急", option: "舀水", result: "展示品品质-1", map: "双点海", evaluation: "负面" },
  { id: "227", dilemma: "情况危急", option: "堵住漏洞（荒野求生）", result: "探险行动时长：-3天, 士气高涨", map: "双点海", evaluation: "正面" },
  { id: "228", dilemma: "情况危急", option: "喝掉涌进来的水", result: "【疾病】泥铲炎", map: "双点海", evaluation: "负面" },
  { id: "229", dilemma: "巨无霸麻烦", option: "人多力量大", result: "探险行动时长：+3天, 生物多样性等级+10%", map: "远方群岛", evaluation: "负面,正面" },
  { id: "230", dilemma: "巨无霸麻烦", option: "边看边学", result: "+50% XP,特质:生态学家", map: "远方群岛", evaluation: "正面" },
  { id: "231", dilemma: "巨无霸麻烦", option: "看来帮不上忙", result: "未知", map: "远方群岛", evaluation: "中性" },
  { id: "232", dilemma: "一道难题", option: "尽量解决", result: "探险行动时长:+7天,生物多样性等级降低", map: "远方群岛", evaluation: "负面" },
  { id: "233", dilemma: "一道难题", option: "竭尽全力", result: "探险行动时长:+15天", map: "远方群岛", evaluation: "负面" },
  { id: "234", dilemma: "国王的巨款", option: "黄金", result: "金钱+15000, 特质：破军杀龙", map: "焦土世界", evaluation: "正面" },
  { id: "235", dilemma: "国王的巨款", option: "魔法药瓶", result: "随行物品（无敌药水）, 特质：破军杀龙", map: "焦土世界", evaluation: "正面" },
  { id: "236", dilemma: "野外漏油事件", option: "救援动物", result: "展示品品质+3, 生物多样性等级-25%", map: "远方群岛", evaluation: "中性" },
  { id: "237", dilemma: "野外漏油事件", option: "清理漏油", result: "展示品品质-1, 生物多样性等级+25%", map: "远方群岛", evaluation: "负面" },
  { id: "238", dilemma: "野外漏油事件", option: "何必做选择（动物分析）", result: "未知", map: "远方群岛", evaluation: "中性" },
  { id: "239", dilemma: "粪山", option: "勇往直前", result: "探险行动时长:-3天,【伤病】拘泥症", map: "远方群岛", evaluation: "中性" },
  { id: "240", dilemma: "粪山", option: "另找出路", result: "探险行动时长：+7天", map: "远方群岛", evaluation: "负面" },
  { id: "241", dilemma: "粪山", option: "屎里逃生", result: "未知", map: "远方群岛", evaluation: "中性" },
  { id: "242", dilemma: "美石相伴", option: "领养这块石头", result: "展示品", map: "远方群岛", evaluation: "正面" },
  { id: "243", dilemma: "美石相伴", option: "不了，谢谢", result: "无事发生", map: "远方群岛", evaluation: "中性" },
  { id: "244", dilemma: "", option: "清理栖息地", result: "未知", map: "远方群岛", evaluation: "中性" },
  { id: "263", dilemma: "杂乱小窝", option: "带走动物", result: "展示品的品质:+1", map: "远方群岛", evaluation: "正面" },
  { id: "245", dilemma: "巢摇过市", option: "带走书", result: "特质：龙之力量", map: "焦土世界", evaluation: "正面" },
  { id: "246", dilemma: "巢摇过市", option: "带走黄金", result: "金钱+15000", map: "焦土世界", evaluation: "正面" },
  { id: "247", dilemma: "巢摇过市", option: "带走魔药", result: "随行物品（无敌药水）", map: "焦土世界", evaluation: "正面" },
  { id: "248", dilemma: "上古战场", option: "帮忙", result: "特质：打工牛马", map: "焦土世界", evaluation: "正面" },
  { id: "249", dilemma: "上古战场", option: "不帮忙", result: "未知", map: "焦土世界", evaluation: "中性" },
  { id: "250", dilemma: "迷失矿洞", option: "继续往前走", result: "未知", map: "焦土世界", evaluation: "中性" },
  { id: "251", dilemma: "迷失矿洞", option: "坐上矿车", result: "士气高涨, 探险行动时长：+3天", map: "焦土世界", evaluation: "中性" },
  { id: "252", dilemma: "迷失矿洞", option: "挖矿装备？（矮人庇佑）", result: "未知", map: "焦土世界", evaluation: "中性" },
  { id: "253", dilemma: "危险峭壁", option: "迎难而上", result: "特质：打工牛马", map: "远方群岛", evaluation: "正面" },
  { id: "254", dilemma: "危险峭壁", option: "小憩片刻", result: "特质：满脑子咖啡豆,经验奖励+50% ", map: "远方群岛", evaluation: "正面" },
  { id: "255", dilemma: "危险峭壁", option: "找个帮手（-10000）", result: "金钱-10000,士气高涨", map: "远方群岛", evaluation: "负面,正面" },
  { id: "256", dilemma: "奇遇", option: "帮忙", result: "【伤病】碎脸, 金钱+1500, 随行物品（富贵有余魔药）", map: "焦土世界", evaluation: "伤病" },
  { id: "257", dilemma: "奇遇", option: "不帮", result: "未知", map: "焦土世界", evaluation: "中性" },
  { id: "258", dilemma: "奇遇", option: "御马之术（斯皮粉多学者）", result: "未知", map: "焦土世界", evaluation: "中性" },
  { id: "259", dilemma: "危机之地", option: "继续前进", result: "探险行动时长：-3天", map: "远方群岛", evaluation: "正面" },
  { id: "260", dilemma: "危机之地", option: "留下除草", result: "探险行动时长:+7天,生物多样性等级降低", map: "远方群岛", evaluation: "负面" },
  { id: "261", dilemma: "沙漠救援行动", option: "潇洒狮幼崽", result: "特质：猫奴", map: "远方群岛", evaluation: "正面" },
  { id: "262", dilemma: "沙漠救援行动", option: "弹跳羚", result: "特质：痴迷哺乳类", map: "远方群岛", evaluation: "正面" },
  { id: "264", dilemma: "你好，魔药商人", option: "力量魔药", result: "随行物品（力量魔药）,金钱-5000", map: "焦土世界", evaluation: "中性" },
  { id: "265", dilemma: "你好，魔药商人", option: "敏捷魔药", result: "随行物品（敏捷魔药）,金钱-5000", map: "焦土世界", evaluation: "中性" },
  { id: "266", dilemma: "你好，魔药商人", option: "今天不嗑药", result: "未知", map: "焦土世界", evaluation: "中性" },
  { id: "267", dilemma: "得意羊羊", option: "绕开（调查勘探）", result: "士气高涨，探险行动时长：-4天", map: "焦土世界", evaluation: "正面" },
  { id: "268", dilemma: "得意羊羊", option: "谈判", result: "未知", map: "焦土世界", evaluation: "中性" },
  { id: "269", dilemma: "得意羊羊", option: "用食物哄它", result: "探险行动时长：-7天", map: "焦土世界", evaluation: "正面" },
  { id: "270", dilemma: "偶遇野人", option: "建造冰堡", result: "探险行动时长：+5天", map: "白骨带", evaluation: "负面" },
  { id: "271", dilemma: "偶遇野人", option: "上前搭话", result: "未知", map: "白骨带", evaluation: "中性" },
 { id: "272", dilemma: "燃烧的怒火", option: "堵住西边的路（拯救祈愿村）", result: "恶龙之怒：仙灵谷调查点已被摧毁", map: "焦土世界", evaluation: "中性" },
   { id: "273", dilemma: "燃烧的怒火", option: "堵住东边的路（拯救仙灵谷）", result: "恶龙之怒：祈愿村调查点已被摧毁", map: "焦土世界", evaluation: "中性" }
];







